/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query GetWords($filter: WordFilter, $first: Int, $after: String) {\n    words(filter: $filter, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          text\n          transcription\n          audioUrl\n          frequencyRank\n          createdAt\n          forms {\n            id\n            formText\n            formType\n          }\n          meanings {\n            id\n            partOfSpeech\n            definitionEn\n            translationRu\n            cefrLevel\n            imageUrl\n            status\n            nextReviewAt\n            reviewCount\n            examples {\n              id\n              sentenceEn\n              sentenceRu\n              sourceName\n            }\n            tags {\n              id\n              name\n            }\n            synonymsAntonyms {\n              id\n              relatedMeaningId\n              relationType\n            }\n          }\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n": typeof types.GetWordsDocument,
    "\n  query GetWord($id: ID!) {\n    word(id: $id) {\n      id\n      text\n      transcription\n      audioUrl\n      frequencyRank\n      createdAt\n      forms {\n        id\n        formText\n        formType\n      }\n      meanings {\n        id\n        wordId\n        partOfSpeech\n        definitionEn\n        translationRu\n        cefrLevel\n        imageUrl\n        status\n        nextReviewAt\n        reviewCount\n        examples {\n          id\n          sentenceEn\n          sentenceRu\n          sourceName\n        }\n        tags {\n          id\n          name\n        }\n        synonymsAntonyms {\n          id\n          relatedMeaningId\n          relationType\n        }\n      }\n    }\n  }\n": typeof types.GetWordDocument,
    "\n  query GetInboxItems {\n    inboxItems {\n      id\n      text\n      sourceContext\n      createdAt\n    }\n  }\n": typeof types.GetInboxItemsDocument,
    "\n  query Suggest($query: String!) {\n    suggest(query: $query) {\n      text\n      transcription\n      translations\n      origin\n      existingWordId\n    }\n  }\n": typeof types.SuggestDocument,
    "\n  query GetStudyQueue($limit: Int) {\n    studyQueue(limit: $limit) {\n      id\n      wordId\n      partOfSpeech\n      definitionEn\n      translationRu\n      cefrLevel\n      imageUrl\n      status\n      nextReviewAt\n      reviewCount\n      examples {\n        id\n        sentenceEn\n        sentenceRu\n        sourceName\n      }\n      tags {\n        id\n        name\n      }\n      synonymsAntonyms {\n        id\n        relatedMeaningId\n        relationType\n      }\n    }\n  }\n": typeof types.GetStudyQueueDocument,
    "\n  query GetStats {\n    stats {\n      totalWords\n      masteredCount\n      learningCount\n      dueForReviewCount\n    }\n  }\n": typeof types.GetStatsDocument,
    "\n  mutation CreateWord($input: CreateWordInput!) {\n    createWord(input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n": typeof types.CreateWordDocument,
    "\n  mutation UpdateWord($id: ID!, $input: CreateWordInput!) {\n    updateWord(id: $id, input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n": typeof types.UpdateWordDocument,
    "\n  mutation DeleteWord($id: ID!) {\n    deleteWord(id: $id)\n  }\n": typeof types.DeleteWordDocument,
    "\n  mutation AddToInbox($text: String!, $sourceContext: String) {\n    addToInbox(text: $text, sourceContext: $sourceContext) {\n      id\n      text\n      sourceContext\n      createdAt\n    }\n  }\n": typeof types.AddToInboxDocument,
    "\n  mutation DeleteInboxItem($id: ID!) {\n    deleteInboxItem(id: $id)\n  }\n": typeof types.DeleteInboxItemDocument,
    "\n  mutation ConvertInboxItem($inboxId: ID!, $input: CreateWordInput!) {\n    convertInboxItem(inboxId: $inboxId, input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n": typeof types.ConvertInboxItemDocument,
    "\n  mutation ReviewMeaning($meaningId: ID!, $grade: Int!) {\n    reviewMeaning(meaningId: $meaningId, grade: $grade) {\n      id\n      wordId\n      partOfSpeech\n      definitionEn\n      translationRu\n      cefrLevel\n      imageUrl\n      status\n      nextReviewAt\n      reviewCount\n      examples {\n        id\n        sentenceEn\n        sentenceRu\n        sourceName\n      }\n      tags {\n        id\n        name\n      }\n      synonymsAntonyms {\n        id\n        relatedMeaningId\n        relationType\n      }\n    }\n  }\n": typeof types.ReviewMeaningDocument,
};
const documents: Documents = {
    "\n  query GetWords($filter: WordFilter, $first: Int, $after: String) {\n    words(filter: $filter, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          text\n          transcription\n          audioUrl\n          frequencyRank\n          createdAt\n          forms {\n            id\n            formText\n            formType\n          }\n          meanings {\n            id\n            partOfSpeech\n            definitionEn\n            translationRu\n            cefrLevel\n            imageUrl\n            status\n            nextReviewAt\n            reviewCount\n            examples {\n              id\n              sentenceEn\n              sentenceRu\n              sourceName\n            }\n            tags {\n              id\n              name\n            }\n            synonymsAntonyms {\n              id\n              relatedMeaningId\n              relationType\n            }\n          }\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n": types.GetWordsDocument,
    "\n  query GetWord($id: ID!) {\n    word(id: $id) {\n      id\n      text\n      transcription\n      audioUrl\n      frequencyRank\n      createdAt\n      forms {\n        id\n        formText\n        formType\n      }\n      meanings {\n        id\n        wordId\n        partOfSpeech\n        definitionEn\n        translationRu\n        cefrLevel\n        imageUrl\n        status\n        nextReviewAt\n        reviewCount\n        examples {\n          id\n          sentenceEn\n          sentenceRu\n          sourceName\n        }\n        tags {\n          id\n          name\n        }\n        synonymsAntonyms {\n          id\n          relatedMeaningId\n          relationType\n        }\n      }\n    }\n  }\n": types.GetWordDocument,
    "\n  query GetInboxItems {\n    inboxItems {\n      id\n      text\n      sourceContext\n      createdAt\n    }\n  }\n": types.GetInboxItemsDocument,
    "\n  query Suggest($query: String!) {\n    suggest(query: $query) {\n      text\n      transcription\n      translations\n      origin\n      existingWordId\n    }\n  }\n": types.SuggestDocument,
    "\n  query GetStudyQueue($limit: Int) {\n    studyQueue(limit: $limit) {\n      id\n      wordId\n      partOfSpeech\n      definitionEn\n      translationRu\n      cefrLevel\n      imageUrl\n      status\n      nextReviewAt\n      reviewCount\n      examples {\n        id\n        sentenceEn\n        sentenceRu\n        sourceName\n      }\n      tags {\n        id\n        name\n      }\n      synonymsAntonyms {\n        id\n        relatedMeaningId\n        relationType\n      }\n    }\n  }\n": types.GetStudyQueueDocument,
    "\n  query GetStats {\n    stats {\n      totalWords\n      masteredCount\n      learningCount\n      dueForReviewCount\n    }\n  }\n": types.GetStatsDocument,
    "\n  mutation CreateWord($input: CreateWordInput!) {\n    createWord(input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n": types.CreateWordDocument,
    "\n  mutation UpdateWord($id: ID!, $input: CreateWordInput!) {\n    updateWord(id: $id, input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n": types.UpdateWordDocument,
    "\n  mutation DeleteWord($id: ID!) {\n    deleteWord(id: $id)\n  }\n": types.DeleteWordDocument,
    "\n  mutation AddToInbox($text: String!, $sourceContext: String) {\n    addToInbox(text: $text, sourceContext: $sourceContext) {\n      id\n      text\n      sourceContext\n      createdAt\n    }\n  }\n": types.AddToInboxDocument,
    "\n  mutation DeleteInboxItem($id: ID!) {\n    deleteInboxItem(id: $id)\n  }\n": types.DeleteInboxItemDocument,
    "\n  mutation ConvertInboxItem($inboxId: ID!, $input: CreateWordInput!) {\n    convertInboxItem(inboxId: $inboxId, input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n": types.ConvertInboxItemDocument,
    "\n  mutation ReviewMeaning($meaningId: ID!, $grade: Int!) {\n    reviewMeaning(meaningId: $meaningId, grade: $grade) {\n      id\n      wordId\n      partOfSpeech\n      definitionEn\n      translationRu\n      cefrLevel\n      imageUrl\n      status\n      nextReviewAt\n      reviewCount\n      examples {\n        id\n        sentenceEn\n        sentenceRu\n        sourceName\n      }\n      tags {\n        id\n        name\n      }\n      synonymsAntonyms {\n        id\n        relatedMeaningId\n        relationType\n      }\n    }\n  }\n": types.ReviewMeaningDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetWords($filter: WordFilter, $first: Int, $after: String) {\n    words(filter: $filter, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          text\n          transcription\n          audioUrl\n          frequencyRank\n          createdAt\n          forms {\n            id\n            formText\n            formType\n          }\n          meanings {\n            id\n            partOfSpeech\n            definitionEn\n            translationRu\n            cefrLevel\n            imageUrl\n            status\n            nextReviewAt\n            reviewCount\n            examples {\n              id\n              sentenceEn\n              sentenceRu\n              sourceName\n            }\n            tags {\n              id\n              name\n            }\n            synonymsAntonyms {\n              id\n              relatedMeaningId\n              relationType\n            }\n          }\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n"): (typeof documents)["\n  query GetWords($filter: WordFilter, $first: Int, $after: String) {\n    words(filter: $filter, first: $first, after: $after) {\n      edges {\n        node {\n          id\n          text\n          transcription\n          audioUrl\n          frequencyRank\n          createdAt\n          forms {\n            id\n            formText\n            formType\n          }\n          meanings {\n            id\n            partOfSpeech\n            definitionEn\n            translationRu\n            cefrLevel\n            imageUrl\n            status\n            nextReviewAt\n            reviewCount\n            examples {\n              id\n              sentenceEn\n              sentenceRu\n              sourceName\n            }\n            tags {\n              id\n              name\n            }\n            synonymsAntonyms {\n              id\n              relatedMeaningId\n              relationType\n            }\n          }\n        }\n        cursor\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n      totalCount\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetWord($id: ID!) {\n    word(id: $id) {\n      id\n      text\n      transcription\n      audioUrl\n      frequencyRank\n      createdAt\n      forms {\n        id\n        formText\n        formType\n      }\n      meanings {\n        id\n        wordId\n        partOfSpeech\n        definitionEn\n        translationRu\n        cefrLevel\n        imageUrl\n        status\n        nextReviewAt\n        reviewCount\n        examples {\n          id\n          sentenceEn\n          sentenceRu\n          sourceName\n        }\n        tags {\n          id\n          name\n        }\n        synonymsAntonyms {\n          id\n          relatedMeaningId\n          relationType\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetWord($id: ID!) {\n    word(id: $id) {\n      id\n      text\n      transcription\n      audioUrl\n      frequencyRank\n      createdAt\n      forms {\n        id\n        formText\n        formType\n      }\n      meanings {\n        id\n        wordId\n        partOfSpeech\n        definitionEn\n        translationRu\n        cefrLevel\n        imageUrl\n        status\n        nextReviewAt\n        reviewCount\n        examples {\n          id\n          sentenceEn\n          sentenceRu\n          sourceName\n        }\n        tags {\n          id\n          name\n        }\n        synonymsAntonyms {\n          id\n          relatedMeaningId\n          relationType\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetInboxItems {\n    inboxItems {\n      id\n      text\n      sourceContext\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query GetInboxItems {\n    inboxItems {\n      id\n      text\n      sourceContext\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query Suggest($query: String!) {\n    suggest(query: $query) {\n      text\n      transcription\n      translations\n      origin\n      existingWordId\n    }\n  }\n"): (typeof documents)["\n  query Suggest($query: String!) {\n    suggest(query: $query) {\n      text\n      transcription\n      translations\n      origin\n      existingWordId\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetStudyQueue($limit: Int) {\n    studyQueue(limit: $limit) {\n      id\n      wordId\n      partOfSpeech\n      definitionEn\n      translationRu\n      cefrLevel\n      imageUrl\n      status\n      nextReviewAt\n      reviewCount\n      examples {\n        id\n        sentenceEn\n        sentenceRu\n        sourceName\n      }\n      tags {\n        id\n        name\n      }\n      synonymsAntonyms {\n        id\n        relatedMeaningId\n        relationType\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetStudyQueue($limit: Int) {\n    studyQueue(limit: $limit) {\n      id\n      wordId\n      partOfSpeech\n      definitionEn\n      translationRu\n      cefrLevel\n      imageUrl\n      status\n      nextReviewAt\n      reviewCount\n      examples {\n        id\n        sentenceEn\n        sentenceRu\n        sourceName\n      }\n      tags {\n        id\n        name\n      }\n      synonymsAntonyms {\n        id\n        relatedMeaningId\n        relationType\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query GetStats {\n    stats {\n      totalWords\n      masteredCount\n      learningCount\n      dueForReviewCount\n    }\n  }\n"): (typeof documents)["\n  query GetStats {\n    stats {\n      totalWords\n      masteredCount\n      learningCount\n      dueForReviewCount\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation CreateWord($input: CreateWordInput!) {\n    createWord(input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation CreateWord($input: CreateWordInput!) {\n    createWord(input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation UpdateWord($id: ID!, $input: CreateWordInput!) {\n    updateWord(id: $id, input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateWord($id: ID!, $input: CreateWordInput!) {\n    updateWord(id: $id, input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteWord($id: ID!) {\n    deleteWord(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteWord($id: ID!) {\n    deleteWord(id: $id)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation AddToInbox($text: String!, $sourceContext: String) {\n    addToInbox(text: $text, sourceContext: $sourceContext) {\n      id\n      text\n      sourceContext\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation AddToInbox($text: String!, $sourceContext: String) {\n    addToInbox(text: $text, sourceContext: $sourceContext) {\n      id\n      text\n      sourceContext\n      createdAt\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation DeleteInboxItem($id: ID!) {\n    deleteInboxItem(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteInboxItem($id: ID!) {\n    deleteInboxItem(id: $id)\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation ConvertInboxItem($inboxId: ID!, $input: CreateWordInput!) {\n    convertInboxItem(inboxId: $inboxId, input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ConvertInboxItem($inboxId: ID!, $input: CreateWordInput!) {\n    convertInboxItem(inboxId: $inboxId, input: $input) {\n      word {\n        id\n        text\n        transcription\n        audioUrl\n        frequencyRank\n        forms {\n          id\n          formText\n          formType\n        }\n        meanings {\n          id\n          partOfSpeech\n          definitionEn\n          translationRu\n          cefrLevel\n          imageUrl\n          status\n          nextReviewAt\n          reviewCount\n          examples {\n            id\n            sentenceEn\n            sentenceRu\n            sourceName\n          }\n          tags {\n            id\n            name\n          }\n          synonymsAntonyms {\n            id\n            relatedMeaningId\n            relationType\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  mutation ReviewMeaning($meaningId: ID!, $grade: Int!) {\n    reviewMeaning(meaningId: $meaningId, grade: $grade) {\n      id\n      wordId\n      partOfSpeech\n      definitionEn\n      translationRu\n      cefrLevel\n      imageUrl\n      status\n      nextReviewAt\n      reviewCount\n      examples {\n        id\n        sentenceEn\n        sentenceRu\n        sourceName\n      }\n      tags {\n        id\n        name\n      }\n      synonymsAntonyms {\n        id\n        relatedMeaningId\n        relationType\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ReviewMeaning($meaningId: ID!, $grade: Int!) {\n    reviewMeaning(meaningId: $meaningId, grade: $grade) {\n      id\n      wordId\n      partOfSpeech\n      definitionEn\n      translationRu\n      cefrLevel\n      imageUrl\n      status\n      nextReviewAt\n      reviewCount\n      examples {\n        id\n        sentenceEn\n        sentenceRu\n        sourceName\n      }\n      tags {\n        id\n        name\n      }\n      synonymsAntonyms {\n        id\n        relatedMeaningId\n        relationType\n      }\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;