// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateWordInput struct {
	Text          string          `json:"text"`
	Transcription *string         `json:"transcription,omitempty"`
	AudioURL      *string         `json:"audioUrl,omitempty"`
	SourceContext *string         `json:"sourceContext,omitempty"`
	Meanings      []*MeaningInput `json:"meanings,omitempty"`
}

type CreateWordPayload struct {
	Word *Word `json:"word"`
}

type DashboardStats struct {
	TotalWords        int `json:"totalWords"`
	MasteredCount     int `json:"masteredCount"`
	LearningCount     int `json:"learningCount"`
	DueForReviewCount int `json:"dueForReviewCount"`
}

type Example struct {
	ID         string         `json:"id"`
	SentenceEn string         `json:"sentenceEn"`
	SentenceRu *string        `json:"sentenceRu,omitempty"`
	SourceName *ExampleSource `json:"sourceName,omitempty"`
}

type ExampleInput struct {
	SentenceEn string  `json:"sentenceEn"`
	SentenceRu *string `json:"sentenceRu,omitempty"`
	SourceName *string `json:"sourceName,omitempty"`
}

type InboxItem struct {
	ID            string  `json:"id"`
	Text          string  `json:"text"`
	SourceContext *string `json:"sourceContext,omitempty"`
	CreatedAt     Time    `json:"createdAt"`
}

type Meaning struct {
	ID               string            `json:"id"`
	WordID           string            `json:"wordId"`
	PartOfSpeech     PartOfSpeech      `json:"partOfSpeech"`
	DefinitionEn     *string           `json:"definitionEn,omitempty"`
	TranslationRu    []string          `json:"translationRu,omitempty"`
	CefrLevel        *string           `json:"cefrLevel,omitempty"`
	ImageURL         *string           `json:"imageUrl,omitempty"`
	Status           LearningStatus    `json:"status"`
	NextReviewAt     *Time             `json:"nextReviewAt,omitempty"`
	ReviewCount      int               `json:"reviewCount"`
	Examples         []*Example        `json:"examples,omitempty"`
	Tags             []*Tag            `json:"tags,omitempty"`
	SynonymsAntonyms []*SynonymAntonym `json:"synonymsAntonyms,omitempty"`
}

type MeaningInput struct {
	PartOfSpeech  PartOfSpeech    `json:"partOfSpeech"`
	DefinitionEn  *string         `json:"definitionEn,omitempty"`
	TranslationRu string          `json:"translationRu"`
	ImageURL      *string         `json:"imageUrl,omitempty"`
	Examples      []*ExampleInput `json:"examples,omitempty"`
	Tags          []string        `json:"tags,omitempty"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Suggestion struct {
	Text           string           `json:"text"`
	Transcription  *string          `json:"transcription,omitempty"`
	Definition     *string          `json:"definition,omitempty"`
	Translations   []string         `json:"translations"`
	Origin         SuggestionOrigin `json:"origin"`
	ExistingWordID *string          `json:"existingWordId,omitempty"`
}

type SynonymAntonym struct {
	ID               string       `json:"id"`
	RelatedMeaningID string       `json:"relatedMeaningId"`
	RelationType     RelationType `json:"relationType"`
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UpdateWordPayload struct {
	Word *Word `json:"word"`
}

type Word struct {
	ID            string      `json:"id"`
	Text          string      `json:"text"`
	Transcription *string     `json:"transcription,omitempty"`
	AudioURL      *string     `json:"audioUrl,omitempty"`
	FrequencyRank *int        `json:"frequencyRank,omitempty"`
	CreatedAt     *Time       `json:"createdAt,omitempty"`
	Forms         []*WordForm `json:"forms,omitempty"`
	Meanings      []*Meaning  `json:"meanings,omitempty"`
}

type WordConnection struct {
	Edges      []*WordEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

type WordEdge struct {
	Cursor string `json:"cursor"`
	Node   *Word  `json:"node"`
}

type WordFilter struct {
	Search *string         `json:"search,omitempty"`
	Status *LearningStatus `json:"status,omitempty"`
	Tags   []string        `json:"tags,omitempty"`
}

type WordForm struct {
	ID       string  `json:"id"`
	FormText string  `json:"formText"`
	FormType *string `json:"formType,omitempty"`
}

type CefrLevel string

const (
	CefrLevelA1 CefrLevel = "A1"
	CefrLevelA2 CefrLevel = "A2"
	CefrLevelB1 CefrLevel = "B1"
	CefrLevelB2 CefrLevel = "B2"
	CefrLevelC1 CefrLevel = "C1"
	CefrLevelC2 CefrLevel = "C2"
)

var AllCefrLevel = []CefrLevel{
	CefrLevelA1,
	CefrLevelA2,
	CefrLevelB1,
	CefrLevelB2,
	CefrLevelC1,
	CefrLevelC2,
}

func (e CefrLevel) IsValid() bool {
	switch e {
	case CefrLevelA1, CefrLevelA2, CefrLevelB1, CefrLevelB2, CefrLevelC1, CefrLevelC2:
		return true
	}
	return false
}

func (e CefrLevel) String() string {
	return string(e)
}

func (e *CefrLevel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CefrLevel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CefrLevel", str)
	}
	return nil
}

func (e CefrLevel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CefrLevel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CefrLevel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ExampleSource string

const (
	ExampleSourceFilm    ExampleSource = "FILM"
	ExampleSourceBook    ExampleSource = "BOOK"
	ExampleSourceChat    ExampleSource = "CHAT"
	ExampleSourceVideo   ExampleSource = "VIDEO"
	ExampleSourcePodcast ExampleSource = "PODCAST"
)

var AllExampleSource = []ExampleSource{
	ExampleSourceFilm,
	ExampleSourceBook,
	ExampleSourceChat,
	ExampleSourceVideo,
	ExampleSourcePodcast,
}

func (e ExampleSource) IsValid() bool {
	switch e {
	case ExampleSourceFilm, ExampleSourceBook, ExampleSourceChat, ExampleSourceVideo, ExampleSourcePodcast:
		return true
	}
	return false
}

func (e ExampleSource) String() string {
	return string(e)
}

func (e *ExampleSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExampleSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExampleSource", str)
	}
	return nil
}

func (e ExampleSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExampleSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExampleSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LearningStatus string

const (
	LearningStatusNew      LearningStatus = "NEW"
	LearningStatusLearning LearningStatus = "LEARNING"
	LearningStatusReview   LearningStatus = "REVIEW"
	LearningStatusMastered LearningStatus = "MASTERED"
)

var AllLearningStatus = []LearningStatus{
	LearningStatusNew,
	LearningStatusLearning,
	LearningStatusReview,
	LearningStatusMastered,
}

func (e LearningStatus) IsValid() bool {
	switch e {
	case LearningStatusNew, LearningStatusLearning, LearningStatusReview, LearningStatusMastered:
		return true
	}
	return false
}

func (e LearningStatus) String() string {
	return string(e)
}

func (e *LearningStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LearningStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LearningStatus", str)
	}
	return nil
}

func (e LearningStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LearningStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LearningStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PartOfSpeech string

const (
	PartOfSpeechNoun      PartOfSpeech = "NOUN"
	PartOfSpeechVerb      PartOfSpeech = "VERB"
	PartOfSpeechAdjective PartOfSpeech = "ADJECTIVE"
	PartOfSpeechAdverb    PartOfSpeech = "ADVERB"
	PartOfSpeechOther     PartOfSpeech = "OTHER"
)

var AllPartOfSpeech = []PartOfSpeech{
	PartOfSpeechNoun,
	PartOfSpeechVerb,
	PartOfSpeechAdjective,
	PartOfSpeechAdverb,
	PartOfSpeechOther,
}

func (e PartOfSpeech) IsValid() bool {
	switch e {
	case PartOfSpeechNoun, PartOfSpeechVerb, PartOfSpeechAdjective, PartOfSpeechAdverb, PartOfSpeechOther:
		return true
	}
	return false
}

func (e PartOfSpeech) String() string {
	return string(e)
}

func (e *PartOfSpeech) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PartOfSpeech(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PartOfSpeech", str)
	}
	return nil
}

func (e PartOfSpeech) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PartOfSpeech) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PartOfSpeech) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RelationType string

const (
	RelationTypeSynonym RelationType = "SYNONYM"
	RelationTypeAntonym RelationType = "ANTONYM"
)

var AllRelationType = []RelationType{
	RelationTypeSynonym,
	RelationTypeAntonym,
}

func (e RelationType) IsValid() bool {
	switch e {
	case RelationTypeSynonym, RelationTypeAntonym:
		return true
	}
	return false
}

func (e RelationType) String() string {
	return string(e)
}

func (e *RelationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RelationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RelationType", str)
	}
	return nil
}

func (e RelationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RelationType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RelationType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SuggestionOrigin string

const (
	SuggestionOriginLocal      SuggestionOrigin = "LOCAL"
	SuggestionOriginDictionary SuggestionOrigin = "DICTIONARY"
)

var AllSuggestionOrigin = []SuggestionOrigin{
	SuggestionOriginLocal,
	SuggestionOriginDictionary,
}

func (e SuggestionOrigin) IsValid() bool {
	switch e {
	case SuggestionOriginLocal, SuggestionOriginDictionary:
		return true
	}
	return false
}

func (e SuggestionOrigin) String() string {
	return string(e)
}

func (e *SuggestionOrigin) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SuggestionOrigin(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SuggestionOrigin", str)
	}
	return nil
}

func (e SuggestionOrigin) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SuggestionOrigin) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SuggestionOrigin) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
