// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AddWordInput struct {
	Text          string          `json:"text"`
	Transcription *string         `json:"transcription,omitempty"`
	AudioURL      *string         `json:"audioUrl,omitempty"`
	Meanings      []*MeaningInput `json:"meanings"`
}

type DashboardStats struct {
	TotalWords        int `json:"totalWords"`
	MasteredCount     int `json:"masteredCount"`
	LearningCount     int `json:"learningCount"`
	DueForReviewCount int `json:"dueForReviewCount"`
}

type Example struct {
	ID         string         `json:"id"`
	SentenceEn string         `json:"sentenceEn"`
	SentenceRu *string        `json:"sentenceRu,omitempty"`
	SourceName *ExampleSource `json:"sourceName,omitempty"`
}

type ExampleInput struct {
	SentenceEn string  `json:"sentenceEn"`
	SentenceRu *string `json:"sentenceRu,omitempty"`
	SourceName *string `json:"sourceName,omitempty"`
}

type Meaning struct {
	ID            string         `json:"id"`
	WordID        string         `json:"wordId"`
	PartOfSpeech  PartOfSpeech   `json:"partOfSpeech"`
	DefinitionEn  *string        `json:"definitionEn,omitempty"`
	TranslationRu string         `json:"translationRu"`
	CefrLevel     *string        `json:"cefrLevel,omitempty"`
	ImageURL      *string        `json:"imageUrl,omitempty"`
	Status        LearningStatus `json:"status"`
	NextReviewAt  *Time          `json:"nextReviewAt,omitempty"`
	ReviewCount   int            `json:"reviewCount"`
	Examples      []*Example     `json:"examples"`
	Tags          []*Tag         `json:"tags"`
}

type MeaningInput struct {
	PartOfSpeech  PartOfSpeech    `json:"partOfSpeech"`
	DefinitionEn  *string         `json:"definitionEn,omitempty"`
	TranslationRu string          `json:"translationRu"`
	ImageURL      *string         `json:"imageUrl,omitempty"`
	Examples      []*ExampleInput `json:"examples,omitempty"`
	Tags          []string        `json:"tags,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Word struct {
	ID            string     `json:"id"`
	Text          string     `json:"text"`
	Transcription *string    `json:"transcription,omitempty"`
	AudioURL      *string    `json:"audioUrl,omitempty"`
	FrequencyRank *int       `json:"frequencyRank,omitempty"`
	Meanings      []*Meaning `json:"meanings"`
}

type WordFilter struct {
	Search *string         `json:"search,omitempty"`
	Status *LearningStatus `json:"status,omitempty"`
	Tags   []string        `json:"tags,omitempty"`
}

type ExampleSource string

const (
	ExampleSourceFilm    ExampleSource = "FILM"
	ExampleSourceBook    ExampleSource = "BOOK"
	ExampleSourceChat    ExampleSource = "CHAT"
	ExampleSourceVideo   ExampleSource = "VIDEO"
	ExampleSourcePodcast ExampleSource = "PODCAST"
)

var AllExampleSource = []ExampleSource{
	ExampleSourceFilm,
	ExampleSourceBook,
	ExampleSourceChat,
	ExampleSourceVideo,
	ExampleSourcePodcast,
}

func (e ExampleSource) IsValid() bool {
	switch e {
	case ExampleSourceFilm, ExampleSourceBook, ExampleSourceChat, ExampleSourceVideo, ExampleSourcePodcast:
		return true
	}
	return false
}

func (e ExampleSource) String() string {
	return string(e)
}

func (e *ExampleSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExampleSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExampleSource", str)
	}
	return nil
}

func (e ExampleSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ExampleSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ExampleSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LearningStatus string

const (
	LearningStatusNew      LearningStatus = "NEW"
	LearningStatusLearning LearningStatus = "LEARNING"
	LearningStatusReview   LearningStatus = "REVIEW"
	LearningStatusMastered LearningStatus = "MASTERED"
)

var AllLearningStatus = []LearningStatus{
	LearningStatusNew,
	LearningStatusLearning,
	LearningStatusReview,
	LearningStatusMastered,
}

func (e LearningStatus) IsValid() bool {
	switch e {
	case LearningStatusNew, LearningStatusLearning, LearningStatusReview, LearningStatusMastered:
		return true
	}
	return false
}

func (e LearningStatus) String() string {
	return string(e)
}

func (e *LearningStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LearningStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LearningStatus", str)
	}
	return nil
}

func (e LearningStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LearningStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LearningStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PartOfSpeech string

const (
	PartOfSpeechNoun      PartOfSpeech = "NOUN"
	PartOfSpeechVerb      PartOfSpeech = "VERB"
	PartOfSpeechAdjective PartOfSpeech = "ADJECTIVE"
	PartOfSpeechAdverb    PartOfSpeech = "ADVERB"
	PartOfSpeechOther     PartOfSpeech = "OTHER"
)

var AllPartOfSpeech = []PartOfSpeech{
	PartOfSpeechNoun,
	PartOfSpeechVerb,
	PartOfSpeechAdjective,
	PartOfSpeechAdverb,
	PartOfSpeechOther,
}

func (e PartOfSpeech) IsValid() bool {
	switch e {
	case PartOfSpeechNoun, PartOfSpeechVerb, PartOfSpeechAdjective, PartOfSpeechAdverb, PartOfSpeechOther:
		return true
	}
	return false
}

func (e PartOfSpeech) String() string {
	return string(e)
}

func (e *PartOfSpeech) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PartOfSpeech(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PartOfSpeech", str)
	}
	return nil
}

func (e PartOfSpeech) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PartOfSpeech) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PartOfSpeech) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
