package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
)

// CreateWord is the resolver for the createWord field.
func (r *mutationResolver) CreateWord(ctx context.Context, input AddWordInput) (*Word, error) {
	panic(fmt.Errorf("not implemented: CreateWord - createWord"))
}

// UpdateWord is the resolver for the updateWord field.
func (r *mutationResolver) UpdateWord(ctx context.Context, id string, input AddWordInput) (*Word, error) {
	panic(fmt.Errorf("not implemented: UpdateWord - updateWord"))
}

// ReviewMeaning is the resolver for the reviewMeaning field.
func (r *mutationResolver) ReviewMeaning(ctx context.Context, meaningID string, grade int) (*Meaning, error) {
	panic(fmt.Errorf("not implemented: ReviewMeaning - reviewMeaning"))
}

// DeleteWord is the resolver for the deleteWord field.
func (r *mutationResolver) DeleteWord(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteWord - deleteWord"))
}

// Words is the resolver for the words field.
func (r *queryResolver) Words(ctx context.Context, filter *WordFilter, limit *int, offset *int) ([]*Word, error) {
	panic(fmt.Errorf("not implemented: Words - words"))
}

// Word is the resolver for the word field.
func (r *queryResolver) Word(ctx context.Context, id string) (*Word, error) {
	panic(fmt.Errorf("not implemented: Word - word"))
}

// StudyQueue is the resolver for the studyQueue field.
func (r *queryResolver) StudyQueue(ctx context.Context, limit *int) ([]*Meaning, error) {
	panic(fmt.Errorf("not implemented: StudyQueue - studyQueue"))
}

// Stats is the resolver for the stats field.
func (r *queryResolver) Stats(ctx context.Context) (*DashboardStats, error) {
	panic(fmt.Errorf("not implemented: Stats - stats"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
