// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
	"github.com/heartmarshall/my-english/internal/model"
)

// Основной инпут для создания слова.
// Позволяет доставать данные из разных источников.
type CreateWordInput struct {
	Text           string                `json:"text"`
	Senses         []*SenseInput         `json:"senses"`
	Images         []*ImageInput         `json:"images,omitempty"`
	Pronunciations []*PronunciationInput `json:"pronunciations,omitempty"`
	CreateCard     bool                  `json:"createCard"`
}

type DashboardStats struct {
	TotalWords    int `json:"totalWords"`
	TotalCards    int `json:"totalCards"`
	NewCards      int `json:"newCards"`
	LearningCards int `json:"learningCards"`
	ReviewCards   int `json:"reviewCards"`
	MasteredCards int `json:"masteredCards"`
	DueToday      int `json:"dueToday"`
}

type ExampleInput struct {
	Sentence    string  `json:"sentence"`
	Translation *string `json:"translation,omitempty"`
	SourceSlug  *string `json:"sourceSlug,omitempty"`
}

type ImageInput struct {
	URL        string  `json:"url"`
	Caption    *string `json:"caption,omitempty"`
	SourceSlug *string `json:"sourceSlug,omitempty"`
}

type Mutation struct {
}

type PronunciationInput struct {
	AudioURL      string  `json:"audioUrl"`
	Transcription *string `json:"transcription,omitempty"`
	Region        *string `json:"region,omitempty"`
	SourceSlug    *string `json:"sourceSlug,omitempty"`
}

type Query struct {
}

type ReviewResult struct {
	Entry        *model.DictionaryEntry `json:"entry"`
	NextReviewAt time.Time              `json:"nextReviewAt"`
}

type SenseInput struct {
	Definition   *string             `json:"definition,omitempty"`
	PartOfSpeech *model.PartOfSpeech `json:"partOfSpeech,omitempty"`
	SourceSlug   *string             `json:"sourceSlug,omitempty"`
	Translations []*TranslationInput `json:"translations,omitempty"`
	Examples     []*ExampleInput     `json:"examples,omitempty"`
}

type SenseRelation struct {
	ID            uuid.UUID    `json:"id"`
	TargetEntryID uuid.UUID    `json:"targetEntryId"`
	Type          RelationType `json:"type"`
}

type SuggestedExample struct {
	Sentence    string  `json:"sentence"`
	Translation *string `json:"translation,omitempty"`
}

type SuggestedImage struct {
	URL          string  `json:"url"`
	ThumbnailURL *string `json:"thumbnailUrl,omitempty"`
	Caption      *string `json:"caption,omitempty"`
}

type SuggestedPronunciation struct {
	AudioURL      string  `json:"audioUrl"`
	Transcription *string `json:"transcription,omitempty"`
	Region        *string `json:"region,omitempty"`
}

type SuggestedSense struct {
	Definition   string              `json:"definition"`
	PartOfSpeech *model.PartOfSpeech `json:"partOfSpeech,omitempty"`
	Examples     []*SuggestedExample `json:"examples"`
	Translations []string            `json:"translations"`
}

// Результат поиска во внешних источниках.
type SuggestionResult struct {
	SourceSlug     string                    `json:"sourceSlug"`
	SourceName     string                    `json:"sourceName"`
	Senses         []*SuggestedSense         `json:"senses"`
	Images         []*SuggestedImage         `json:"images"`
	Pronunciations []*SuggestedPronunciation `json:"pronunciations"`
}

type TranslationInput struct {
	Text       string  `json:"text"`
	SourceSlug *string `json:"sourceSlug,omitempty"`
}

type UpdateWordInput struct {
	Text   *string       `json:"text,omitempty"`
	Senses []*SenseInput `json:"senses,omitempty"`
}

type WordFilter struct {
	Search       *string              `json:"search,omitempty"`
	HasCard      *bool                `json:"hasCard,omitempty"`
	PartOfSpeech *model.PartOfSpeech  `json:"partOfSpeech,omitempty"`
	Limit        *int                 `json:"limit,omitempty"`
	Offset       *int                 `json:"offset,omitempty"`
	SortBy       *model.WordSortField `json:"sortBy,omitempty"`
	SortDir      *model.SortDirection `json:"sortDir,omitempty"`
}

type RelationType string

const (
	RelationTypeSynonym     RelationType = "SYNONYM"
	RelationTypeAntonym     RelationType = "ANTONYM"
	RelationTypeRelated     RelationType = "RELATED"
	RelationTypeCollocation RelationType = "COLLOCATION"
)

var AllRelationType = []RelationType{
	RelationTypeSynonym,
	RelationTypeAntonym,
	RelationTypeRelated,
	RelationTypeCollocation,
}

func (e RelationType) IsValid() bool {
	switch e {
	case RelationTypeSynonym, RelationTypeAntonym, RelationTypeRelated, RelationTypeCollocation:
		return true
	}
	return false
}

func (e RelationType) String() string {
	return string(e)
}

func (e *RelationType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RelationType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RelationType", str)
	}
	return nil
}

func (e RelationType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RelationType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RelationType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
